### ISSUE TITLE
Optimize traffic utilization

### ISSUE THREAD

**Issue by bosik** [bosik/diacomp#81]
App (ver. 2.7.1) consumes ~8Mb per day
- [x] #89 Foods/dishes keep syncing until app is restarted
- [x] #90 Sync progress is lost on error

---
- [x] #91 Quick zip data import
